### ISSUE TITLE
`level-geospatial` が壊れていて逆ジオコーディングが動かない

### ISSUE THREAD

**Issue by yuiseki** [uedayou/japan-address-search#1]
## 期待した動作

`japan-address-search --lat 35.675551 --lng 139.750413` で住所が得られる

## 実際の動作

以下のような出力が表示される

```
{
  "@context": "https://imi.go.jp/ns/core/context.jsonld",
  "メタデータ": {
    "@type": "文書型",
    "説明": "検索中にエラーが発生しました"
  }
}
```

## 原因

`lib/rg-main.js` の42行目で使われている `level-geospatial` が、 `levelup` v5.0.0 で削除された `start` と `end` のrange optionを使っている
https://github.com/uedayou/japan-address-search/blob/master/lib/rg-main.js#L42
https://github.com/richorama/level-geospatial/blob/master/lib/level-geospatial.js#L96
https://github.com/Level/levelup/blob/master/UPGRADING.md?rgh-link-date=2021-05-02T01%3A45%3A43Z#500

## 修正方法案

- `./node_modules/level-geospatial/lib/level-geospatial.js` の111行目、112行目の `start` と `end` を `gte` と `lte` に書き換える
  - `level-geospatial` にPull Requestを出しました（が、メンテナンスが続いているのか、取り込まれるのかは不明）
  - https://github.com/richorama/level-geospatial/pull/7
- levelup v5未満に依存関係を固定する

**Comment by uedayou** [comment]
@yuiseki いろいろご提案ありがとうございました。私のほうでも状況確認し、修正したいと思います。

**Comment by uedayou** [comment]
@yuiseki 遅くなりましたが、お知らせいただいた不具合に対応しました。
`35.675551, 139.750413` で検索できることを確認し、こちらを利用したテストコードも追加しました。
https://github.com/uedayou/japan-address-search/commit/1c7ef18a75e822f5672dba2197ced43e4fe08f3c
私の対応時に `level-geospatial` のほうでマージされていましたので、スムーズに対応することができました。
@yuiseki さんには大変感謝しています。ありがとうございました。
もし再発するようでしたら、ご連絡ください。よろしくお願いいたします。
